name: qs_dart
description: A query string encoding and decoding library for Dart. Ported from qs for JavaScript.
version: 1.7.1
homepage: https://techouse.github.io/qs/
repository: https://github.com/techouse/qs
issue_tracker: https://github.com/techouse/qs/issues
documentation: https://pub.dev/documentation/qs_dart/latest/
funding:
  - https://github.com/sponsors/techouse
  - https://paypal.me/ktusar

environment:
  sdk: ^3.0.0

dependencies:
  collection: ^1.18.0
  equatable: ^2.0.7
  meta: ^1.9.1

dev_dependencies:
  cli_script: ^1.0.0
  euc: ^1.0.6+8
  lints: ^6.0.0
  path: ^1.9.0
  test: ^1.25.5

topics:
  - url
  - query
  - query-string
  - encode
  - decode

screenshots:
  - description: The qs_dart package logo.
    path: logo.png
